### PR TITLE
remove unnecessary command

### PR DESCRIPTION
**Pull request by breandan**

### CODE REVIEW

**Comment by fgolemo** [comment]
Are you sure if you just do `docker-compose up` it will still try to pull the latest image? Because I did a quick test and it didn't seem to be the case. If I already had the image downloaded, it wouldn't even look if there is a newer one.

**Comment by abdelq** [comment]
@fgolemo It won't pull if there is an image locally. So for a first run `docker-compose up` is enough.

**Comment by breandan** [comment]
It will depend on what you want your update mechanism to be, `git pull` or `docker pull`. If we're auto-building on Docker cloud and you expect users to `git clone` only once, then `docker-compose pull && docker-compose up`. Otherwise, `git pull && docker-compose up --build` will also work.

**Comment by fgolemo** [comment]
IDK what's objectively the better way, but I feel like it would be easier if for the simulator we would provide the containers (i.e. users never builds themselves) and thus `docker-compose pull`. But yeah, you're the expert. What do you think? For the agent there shouldn't be any updates (in a perfect world).

**Comment by breandan** [comment]
Not an expert, but sure, let’s stick with `docker-compose pull`. We’ll need to set up auto-builds for these, either you can do this or I can with admin permissions, cf. https://duckietown.slack.com/archives/CAPMS2DD5/p1531756819000069?thread_ts=1531751944.000287&channel=CAPMS2DD5&message_ts=1531756819.000069

**Pull request closed without merging**
